### ISSUE TITLE
infer-ncnn-model.py 报错 ValueError: not enough values to unpack (expected 4, got 0)

### ISSUE THREAD

**Issue by wilsonloo** [meituan/YOLOv6#859]
### Before Asking

- [X] I have read the [README](https://github.com/meituan/YOLOv6/blob/main/README.md) carefully. 我已经仔细阅读了README上的操作指引。

- [X] I want to train my custom dataset, and I have read the [tutorials for training your custom data](https://github.com/meituan/YOLOv6/blob/main/docs/Train_custom_data.md) carefully and organize my dataset correctly; (FYI: We recommand you to apply the config files of xx_finetune.py.) 我想训练自定义数据集，我已经仔细阅读了训练自定义数据的教程，以及按照正确的目录结构存放数据集。（FYI: 我们推荐使用xx_finetune.py等配置文件训练自定义数据集。）

- [X] I have pulled the latest code of main branch to run again and the problem still existed. 我已经拉取了主分支上最新的代码，重新运行之后，问题仍不能解决。

### Search before asking

- [X] I have searched the YOLOv6 [issues](https://github.com/meituan/YOLOv6/issues) and found no similar questions.

### Question

使用自己的数据成功训练出一个模型，并通过toos/infer.py 能够正常且高准确率地检测出我所需要的对象类型。该模型使用yolov6s.py 配置生成初始模型，再使用yolov6s_fineturn.py 进行对初始模型后续训练，目录结构是：
![图片](https://github.com/meituan/YOLOv6/assets/11910639/ae51efca-4a17-4288-8851-681855805438)
YOLOv6 即为当前meituan/YOLOv6.git

# 训练过程：
训练脚本train.sh ：
```sh
#!/bin/bash

# 用自己的数据集训练出初始模型
# cd YOLOv6 && python tools/train.py --name benben --conf-file ../configs/yolov6s.py --output-dir ../runs/train --data-path ../benben.yaml --rect --device 0 --workers 16 --epochs 400

# 使用自己的初始模型继续训练
cd YOLOv6 && python tools/train.py --name benben --conf-file ../configs/yolov6s_finetune.py --output-dir ../runs/train --data-path ../benben.yaml --rect --device 0 --workers 16 --epochs 4000

```

其中 benben.yaml 定义自己的class分类， 和具体的train/val 信息:
```yaml
train:
  - /home/wilson/workstation/benben/data/images/train/A
  - /home/wilson/workstation/benben/data/images/train/B
  - /home/wilson/workstation/benben/data/images/train/C
  - /home/wilson/workstation/benben/data/images/train/D
  - /home/wilson/workstation/benben/data/images/train/E
  - /home/wilson/workstation/benben/data/images/train/F
  - /home/wilson/workstation/benben/data/images/train/dup
  - /home/wilson/workstation/benben/data/images/train/dup_right
val:
  - /home/wilson/workstation/benben/data/images/val/A
  - /home/wilson/workstation/benben/data/images/val/B
  - /home/wilson/workstation/benben/data/images/val/C
  - /home/wilson/workstation/benben/data/images/val/D
  - /home/wilson/workstation/benben/data/images/val/E
  - /home/wilson/workstation/benben/data/images/val/F
  
nc: 3
is_coco: False

# class names
names: ['brake', 'turn_left', 'turn_right']
```

最后生成有效的模型为：weights/best_ckpt.pt， 通过YOLOv6/toos/infer.py 能够正常且高准确率地检测出我所需要的对象类型, 符合我的预期。

# 导出ncnn过程：
参考https://github.com/meituan/YOLOv6/tree/main/deploy/NCNN 的说明，编写个导出脚本 export_2_ncnn.sh：
```sh
curr_loc=`pwd`

echo 'exporting yolov6 model to torch format ...'
# export yolov6.pt to torch format
cd YOLOv6 && python ./deploy/NCNN/export_torchscript.py \
	--weights ../weights/best_ckpt.pt \
        --img 640 640 \
        --batch 1	

cd $curr_loc
echo 'exporting torch format to ncnn ...'
mv ./weights/best_ckpt.torchscript ./weights/ncnn
cd ./tools/export_2_ncnn && ./pnnx-20230524-ubuntu/pnnx ../../weights/ncnn/best_ckpt.torchscript \
    inputshape=[1,3,320,320]f32 \
    inputshape2=[1,3,640,640]f32 \
    device=gpu/cpu
```
最终能够生成几个param/bin 文件：
![图片](https://github.com/meituan/YOLOv6/assets/11910639/3615bd97-6d2d-4fe0-af7e-ae0e2b38bcc6)

# 使用ncnn过程：
同样参考 https://github.com/meituan/YOLOv6/tree/main/deploy/NCNN 使用 deploy/NCNN/infer-ncnn-model.py 进行测试：
```sh
cd YOLOv6 && python deploy/NCNN/infer-ncnn-model.py \
    ../data/images/test/A194.png \
    ../weights/ncnn/best_ckpt.ncnn.param \
    ../weights/ncnn/best_ckpt.ncnn.bin \
    --img-size 640 640 \
    --max-stride 32 \
    --show
```
一开始报错说 no module named ncnn, 是infer-ncnn-model.py 里有import ncnn； 通过 pip install ncnn 成功安装ncnn模块（通过pip list 得知 ncnn版本号为1.0.20230517），重新执行infer-ncnn-model.py 就报错了：
![图片](https://github.com/meituan/YOLOv6/assets/11910639/296b1d99-a5fd-435e-9cf7-3a458f116ae4)
